# Generated by Django 6.0.1 on 2026-01-22 17:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('email_responsable', models.EmailField(help_text='Correo del administrativo a cargo', max_length=254)),
                ('prioridad_base', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_hash', models.CharField(db_index=True, max_length=64)),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='evidencias/%Y/%m/')),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('PROC', 'En Proceso'), ('RES', 'Resuelto'), ('RECH', 'Rechazado/Spam')], default='PEND', max_length=4)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('comentario_admin', models.TextField(blank=True, help_text='Notas internas de la resolución')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.categoria')),
            ],
        ),
    ]
